#!/usr/bin/env python3
"""Emit int8_t sin_q7[256] -- one full turn in 256 binary-angle units, Q0.7."""

import math

TURN = 256
SCALE = 127

vals = [round(SCALE * math.sin(2 * math.pi * i / TURN)) for i in range(TURN)]
assert all(-127 <= v <= 127 for v in vals)
assert all(vals[(i + TURN // 4) % TURN] == round(SCALE * math.cos(2 * math.pi * i / TURN))
           for i in range(TURN))

with open("trig_q7.h", "w") as f:
    w = f.write
    w("/* Generated by gen_trig.py -- do not edit. */\n")
    w("#ifndef TRIG_Q7_H\n#define TRIG_Q7_H\n\n#include <stdint.h>\n\n")
    w(f"#define BAM_TURN     {TURN}\n")
    w(f"#define BAM_QUARTER  {TURN // 4}\n")
    w(f"#define TRIG_Q7_ONE  {SCALE}\n")
    w("#define cos_q7(a) (sin_q7[((a) + BAM_QUARTER) & (BAM_TURN - 1)])\n\n")
    w(f"static const int8_t sin_q7[{TURN}] = {{\n")
    for i in range(0, TURN, 16):
        w("    " + ",".join(f"{v:4d}" for v in vals[i:i + 16]) + ",\n")
    w("};\n\n#endif\n")
print(f"trig_q7.h: {TURN} entries, range [{min(vals)}, {max(vals)}]")
